apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule
  labels:
    app: train-schedule
spec
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    labels:
      app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: paungui/train-schedule:${env.BUILD_NUMBER}
        ports:
        - containerPort: 8080
